name 'OCPinstall'
maintainer 'Alex Eusman'
maintainer_email 'aeus@jhu.edu'
license 'all_rights'
description 'Installs/Configures OCPinstall'
long_description 'Installs/Configures OCPinstall'
version '0.2.0'

depends 'apt', '~> 2.9.2'
depends 'mysql2_chef_gem', '~> 1.0.0'
depends 'mysql', '~> 6.1.2'
depends 'database', '~> 4.0.9'
depends 'poise-python', '~> 1.2.0'
depends 'git', '~> 4.3.5'
depends 'uwsgi', '~> 0.1.2'
