default['OCPinstall']['database']['localhost'] = '127.0.0.1'
default['OCPinstall']['database']['rootname'] = 'root'
default['OCPinstall']['database']['rootpass'] = 'neurons'
default['OCPinstall']['database']['startfile'] = 'setupSQL.sql'
default['OCPinstall']['database']['socket'] = '/run/mysql-default/mysqld.sock'
default['OCPinstall']['database']['setup_file'] = '/tmp/setupSQL.sql'
set['apt']['compile_time_update'] = 'true'
